### ISSUE TITLE
incorrectly wrapping list items

### ISSUE THREAD

**Issue by garretwilson** [AnWeber/atom-htmltidy#5]
I have the following options:

```
{"input-xml" : true, "output-xml" : true, "indent" : true, "indent-with-tabs" : true, "wrap" : 0}
```

I have the following input:

```
<ul>
  <li><code>args4j:args4j:2.32</code></li>
</ul>
```

atom-htmltidy wraps that to:

```
    <ul>
        <li>
            <code>args4j:args4j:2.32</code>
        </li>
    </ul>
```

Why the newlines inside `<li>`? How do I get rid of them? `<code>` is an inline element --- there is no need for wrapping.

**Comment by AnWeber** [comment]
the atom plugin is just a wrapper for [Tidy-HTML5](http://www.htacg.org/tidy-html5/), [Documentation](http://api.html-tidy.org/tidy/quickref_5.1.25.html). 

In my opinion the problem is the option "output-xml". If this option is set html-tidy interprets all tags as block level element tags. In my project I don't use this option anymore ([htmltidy.txt](https://github.com/AnWeber/atom-htmltidy/files/82944/htmltidy.txt))

If I couldn't help, please open an issue [here](https://github.com/htacg/tidy-html5/issues). 

Thanks

**Comment by garretwilson** [comment]
> In my opinion the problem is the option "output-xml"

You didn't try it did you? You made an assumption about the problem, didn't test the provided source, and closed the issue.

**Comment by AnWeber** [comment]
Yes, because it is an known issue at [tidy-html](https://github.com/htacg/tidy-html5/issues/332)

**Comment by garretwilson** [comment]
But I see it still occurring without the output-xml option. That's why I asked if you tested it.

**Comment by AnWeber** [comment]
Yes, I tested it. I`ve got the same output on the command line by using tidy.exe. Using the option 'new-inline-tags' didn't solve the problem. Please open an issue [here](https://github.com/htacg/tidy-html5/issues). 

Thanks.
